# Generated by Django 2.2.14 on 2021-11-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_auto_20211103_0459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='ShortURL',
        ),
    ]
